name: dart_console2
version: 2.0.0
homepage: https://github.com/timsneath/dart_console
description: A helper library for command-line applications that need more control over input/output than the standard library provides. This is a placeholder until dart_console releases an upgraded version with ffi 2.x.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  ffi: ^2.0.1
  win32: ^2.0.0
  intl: ^0.17.0
dev_dependencies: 
  lints: ^2.0.0
  test: ^1.17.10
